[project]
name = "self-whisper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai>=1.70.0",
    "pyperclip>=1.9.0",
]
